import { Providers } from './providers'

import type { Metadata } from "next";
import { RocknRoll_One } from "next/font/google";
const rocknRollOne = RocknRoll_One({ subsets: ["latin"], weight: ["400"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={rocknRollOne.className}><Providers>{children}</Providers></body>
    </html>
  );
}
